appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wPCP+hVKj7ZSW9RwAG9yUx0oBaxIf5JTswk4zECc3LuzhAigEK1MrA/ipyvD9Ju4rnHbPdiNAUChz4TheN3BLOCL5WECfYSvF9FiKmWsJA0eCD4EYZ/fOdKQCabUtNdnhZSlxN9Xo1GK1qjyYVvYWT6o/R9XpVecoRhMhL10tnIX1N9wmgaNReEYB3b2m0SBo/61xcoIZkoIcagdcNNZ9MEgghff3Kc3qw6LVVVnnj2AD6A01GgfAMm5aNNpptwEpENu+Uvouz0JUI1Iw60JGq9q+x/vz6aqnraKZjzf9F0X099S8HAYuoax97B1hpsl4YbG74kzfd1CucbhY4jqwRWyLeZnsik3uwLfe/k/juuVeyC9AS5m8h2qUhzJoQFJrClDu6H4e3WUnmq8h10AClEDOewIEvPjtP7Ntvtb6WNthR2+DUuNh+wqpbdxsnrfvMlMRDEHnfB3oVnivkA/zQZmTq/JfNQx/hRkBGllROLK8iD23DM09CJxy+w/s9WVpGg/OmeI0O8LkHevKe372qXG68A2tP6rdYyx1grfOy8e5iOTN8NTtIRMVs7Romwg8NDXQOiUxNF70xRRYGtDxjc8qIQeNgwrelKxx2ItgZe1PKzcsQty7wfa2hyO7wvS2DJKSIBNp778HdLqtxnxlXTp5obJLTh84kAkBWmFqsY=}
provider:
  win: azure
bot:
  automerge: true
